pair_prompt = [
    {
        "image": "Neptune’s upper atmosphere seen in a hyper-realistic dark space documentary style, a side-lit blue planetary limb suspended in a deep black universe, faint auroral glow hovering across the mid-latitudes instead of the poles, the light stretched thin across the upper atmosphere like a weak suspended veil, methane haze softly absorbing the glow, immense scale, high contrast lighting, scientifically realistic astronomy visualization, terrifying and majestic mood, ultra-detailed, 16:9, no text, no watermark, no spacecraft, no humans, no extra planets, no rings, no magical glow, no portal effects, stable single continuous environment, one dominant subject.",
        "video": "Use the provided image as the exact first frame, preserve the same subject, preserve the same composition, preserve the same environment, preserve the same lighting direction, preserve the same color palette, preserve the same scale relationship, one continuous shot, no cuts, no transitions, no scene change, no time jump, no object transformation, no new objects introduced, no new celestial bodies, no text, no labels, no UI, no camera shake, no zoom, no push-in, 60fps, 16:9, no sound. Camera motion type: Locked-off / internal motion only. The upper atmospheric auroral veil drifts very slowly across Neptune’s mid-latitude limb, with faint thermospheric haze softly breathing and wavering in place while the subject size remains constant."
    },
    {
        "image": "Extreme close observational view of Neptune’s upper atmosphere, focusing on irregular auroral patches embedded in the thin thermospheric haze above the cloud tops, the glow appears scattered, broken, and uneven, drifting across the middle of the planet rather than gathering at a pole, soft blue atmospheric gradients, subtle haze layering, hyper-realistic space documentary style, scientifically realistic, immense scale, high contrast, ultra-detailed, 16:9, no text, no watermark, no spacecraft, no extra objects, no fantasy effects.",
        "video": "Use the provided image as the exact first frame, preserve the same subject, preserve the same composition, preserve the same environment, preserve the same lighting direction, preserve the same color palette, preserve the same scale relationship, one continuous shot, no cuts, no transitions, no scene change, no time jump, no object transformation, no new objects introduced, no text, no labels, no UI, no camera shake, no zoom, 60fps, 16:9, no sound. Camera motion type: Parallax hold. Minimal parallax between the upper atmospheric haze and the deeper cloud deck, while the irregular auroral patches brighten slightly, dim slightly, and 'breathe' unevenly, never forming a ring and never moving to the poles."
    },
    {
        "image": "A wide documentary shot of Neptune’s curved upper atmosphere with faint auroral light crawling laterally across the mid-latitude limb, clearly not tied to any polar region or surface geography, the planet’s cloud bands are visible beneath while the glow floats higher in the upper atmospheric layer, deep black universe, cold blue palette, hyper-realistic cosmic documentary style, scientifically realistic astronomy visualization, ultra-detailed, 16:9, no text, no watermark, no spacecraft, no humans, no extra planets, no artificial ring structures.",
        "video": "Use the provided image as the exact first frame, preserve the same subject, preserve the same composition, preserve the same environment, preserve the same lighting direction, preserve the same color palette, preserve the same scale relationship, one continuous shot, no cuts, no transitions, no scene change, no time jump, no object transformation, no new objects introduced, no text, no labels, no UI, no camera shake, no zoom, 60fps, 16:9, no sound. Camera motion type: Slow lateral slide. The camera slides very slowly along the image plane while the faint upper-atmospheric glow crawls sideways across Neptune’s middle latitudes, clearly drifting instead of staying fixed at a pole, with only subtle cloud-band advection below."
    },
    {
        "image": "A layered atmospheric shot of Neptune showing the relationship between the darker deeper atmosphere below and the faint auroral glow above, the upper atmosphere illuminated by scattered thin light while the underlying cloud deck remains darker and heavier, visually suggesting that the light follows an unseen hidden force below rather than the visible geography, no magnetic field lines shown, only physical consequences, hyper-realistic dark documentary style, scientifically realistic astronomy visualization, cold blue and black palette, high contrast lighting, ultra-detailed, 16:9, no text, no watermark, no spacecraft, no humans, no infographic.",
        "video": "Use the provided image as the exact first frame, preserve the same subject, preserve the same composition, preserve the same environment, preserve the same lighting direction, preserve the same color palette, preserve the same scale relationship, one continuous shot, no cuts, no transitions, no scene change, no time jump, no object transformation, no new objects introduced, no text, no labels, no UI, no camera shake, no zoom, 60fps, 16:9, no sound. Camera motion type: Edge-to-edge survey. Slowly survey across the layered atmosphere from the darker lower region to the faint glowing upper thermosphere, showing the upper glow responding while the deeper atmosphere remains shadowed and heavy, implying a hidden underlying cause without showing any field lines or graphic effects."
    },
    {
        "image": "Neptune’s upper atmosphere portrayed as almost invisible, a whisper-thin thermospheric glow barely detectable against the darkness, the faint aurora nearly lost inside the cold blue haze, a scene designed to express why it remained unseen for thirty years, extremely subtle luminous patches, vast negative space, eerie isolation, hyper-realistic space documentary style, scientifically realistic, high contrast, ultra-detailed, 16:9, no text, no watermark, no spacecraft, no humans, no extra celestial bodies, no fantasy effects.",
        "video": "Use the provided image as the exact first frame, preserve the same subject, preserve the same composition, preserve the same environment, preserve the same lighting direction, preserve the same color palette, preserve the same scale relationship, one continuous shot, no cuts, no transitions, no scene change, no time jump, no object transformation, no new objects introduced, no text, no labels, no UI, no camera shake, no zoom, no push-in, 60fps, 16:9, no sound. Camera motion type: Telephoto compression hold. Keep the frame almost motionless while the nearly invisible auroral signal flickers at the threshold of visibility inside the upper haze, fading in and out so weakly that it feels hidden by the atmosphere itself."
    },
    {
        "image": "Neptune’s upper atmosphere in 1989, visualized as a hotter and more energized thermosphere, the atmospheric limb appears expanded and more thermally active, faint upper haze glowing with stronger warmth and tension, subtle shimmering structure above the cloud tops, still dark and realistic, scientifically plausible, representing a thermospheric temperature near 750 Kelvin, hyper-realistic dark space documentary style, immense scale, high contrast lighting, ultra-detailed, 16:9, no text, no watermark, no spacecraft, no humans, no labels, no infographic.",
        "video": "Use the provided image as the exact first frame, preserve the same subject, preserve the same composition, preserve the same environment, preserve the same lighting direction, preserve the same color palette, preserve the same scale relationship, one continuous shot, no cuts, no transitions, no scene change, no time jump, no object transformation, no new objects introduced, no text, no labels, no UI, no camera shake, no zoom, 60fps, 16:9, no sound. Camera motion type: Subtle orbital micro-pan. Keep a fixed camera distance while the hotter 1989 thermosphere shows slightly more active shimmering in the upper atmospheric layer, with gentle heat-like instability and a stronger suspended glow above the cloud tops, emphasizing a hotter, more expanded upper atmosphere."
    },
    {
        "image": "Neptune’s upper atmosphere in 2023, matched to the previous framing for continuity, but now much cooler and calmer, the thermosphere appears more subdued, dimmer, less expanded, and less energized, the faint upper atmospheric glow reduced and quieter, visually representing the dramatic drop to about 358 Kelvin, hyper-realistic dark space documentary style, scientifically realistic astronomy visualization, cold blue-black palette, high contrast lighting, ultra-detailed, 16:9, no text, no watermark, no spacecraft, no humans, no labels, no infographic, one dominant subject.",
        "video": "Use the provided image as the exact first frame, preserve the same subject, preserve the same composition, preserve the same environment, preserve the same lighting direction, preserve the same color palette, preserve the same scale relationship, one continuous shot, no cuts, no transitions, no scene change, no time jump, no object transformation, no new objects introduced, no text, no labels, no UI, no camera shake, no zoom, 60fps, 16:9, no sound. Camera motion type: Locked-off / internal motion only. Match the previous shot’s framing but animate a calmer 2023 thermosphere, with dimmer and less expanded upper haze, weaker glow, slower atmospheric breathing, and a more subdued energy state, clearly conveying that the temperature has dropped dramatically compared with the earlier hotter state."
    }
]
