from scripts.git.services.command_runner import command_runner

command_runner.run(command_runner.command_manager.git_pull)
command_runner.run(command_runner.command_manager.pip_install_requirements)
